name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # dump-context:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Dump github context
  #     run: echo "$GITHUB_CONTEXT"
  #     shell: bash
  #     env:
  #       GITHUB_CONTEXT: ${{ toJson(github) }}

  build-server:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}-server:latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Docker image to Docker GitHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: $IMAGE_TAG

  build-client:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}-client:latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Docker image to Docker GitHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: $IMAGE_TAG
