name: "Terraform Azure"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  TF_DIRECTORY: "${{github.workspace}}/.terraform/azure"

jobs:
  terraform_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIRECTORY }}
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_DIRECTORY }}
